name: Deploy Frontend via Amplify Webhook

permissions:
  contents: read

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:
    inputs:
      reason:
        description: "Optional note for the deploy log"
        required: false

jobs:
  trigger-amplify-webhook:
    name: Trigger Amplify Frontend Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Call Amplify webhook
        env:
          AMPLIFY_WEBHOOK_URL: ${{ secrets.AMPLIFY_WEBHOOK_URL }}
          DEPLOY_REASON: ${{ github.event.inputs.reason || '' }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          if [ -z "$AMPLIFY_WEBHOOK_URL" ]; then
            echo "Missing AMPLIFY_WEBHOOK_URL secret." >&2
            exit 1
          fi

          payload=$(python3 .github/workflows/amplify_webhook_payload.py)

          response_file=$(mktemp)
          status=$(curl -sSL -o "$response_file" -w "%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "$AMPLIFY_WEBHOOK_URL")

          cp "$response_file" "$RUNNER_TEMP/amplify-webhook-response.json"
          printf '%s' "$status" > "$RUNNER_TEMP/amplify-webhook-status.txt"

          if [ "$status" -lt 200 ] || [ "$status" -ge 300 ]; then
            echo "Failed to trigger Amplify webhook (status: $status)" >&2
            cat "$response_file" >&2
            exit 1
          fi

          echo "Amplify webhook triggered successfully (status: $status)."
          echo "Response:\n"
          cat "$response_file"

      - name: Upload webhook response
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: amplify-webhook-response
          path: |
            ${{ runner.temp }}/amplify-webhook-response.json
            ${{ runner.temp }}/amplify-webhook-status.txt
          if-no-files-found: ignore
